### ISSUE TITLE
Invalid XML

### ISSUE THREAD

**Issue by rosskevin** [sj26/rspec_junit_formatter#33]
On bamboo, I find this exception in the log parsing the `rspec.xml`

```java
2015-09-01 18:15:42,773 ERROR [pool-16-thread-1] [TestCollationServiceImpl] Failed to parse test result file "/apps/bamboo-agent/xml-data/build-dir/AFC-DEV-JOB1/target/test-reports/rspec.xml"
org.xml.sax.SAXParseException; lineNumber: 1749; columnNumber: 1; Content is not allowed in trailing section.
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.atlassian.bamboo.build.test.junit.JunitTestResultsParser.parse(JunitTestResultsParser.java:90)
        at com.atlassian.bamboo.build.test.junit.JunitTestReportCollector.collect(JunitTestReportCollector.java:40)
        at com.atlassian.bamboo.build.test.TestCollationServiceImpl$1$1.run(TestCollationServiceImpl.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

The file is large, so heres a snippet with line numbers on the left:

```
1746 <testcase classname="spec.app.support.period_spec" name="Acme::Period yearly non-leap slicing time out of the whole period #prorated_percentage has correct value for February" file="./spec/app/support/period_spec.rb" time="0.8     83298"/>
1747   <testcase classname="spec.lib.form.validations.active_model.phone_validator_spec" name="Acme::Form::Validations::ActiveModel::UniquenessValidator #field_validator_specifications" file="./spec/lib/form/validations/active_model/     phone_validator_spec.rb" time="0.965486"/>
1748 </testsuite>
1749 onview-4.2.4/lib/action_view/template.rb:145:in `block in render'
1750 /home/apps/.rvm/gems/ruby-2.2.0@acme/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
1751 /home/apps/.rvm/gems/ruby-2.2.0@acme/gems/actionview-4.2.4/lib/action_view/template.rb:333:in `instrument'
1752 /home/apps/.rvm/gems/ruby-2.2.0@acme/gems/actionview-4.2.4/lib/action_view/template.rb:143:in `render'

...

1814 ./lib/acme/spec/spec_helper.rb:70:in `block (2 levels) in <top (required)>'
1815 ./lib/acme/spec/spec_helper.rb:31:in `block (2 levels) in <top (required)>'
1816 /home/apps/.rvm/gems/ruby-2.2.0@acme/gems/rspec-wait-0.0.7/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>']]>
1817     </failure>
1818   </testcase> 
```

It appears that there is failure output without an opening tag.  Note that this is being run with `parallel_tests`, so I'm not sure if this file is being written/merged properly with 8 test processes running.

**Comment by rosskevin** [comment]
I found this in parallel_tests, which I'm not doing:

```
--format RspecJunitFormatter
--out tmp/rspec<%= ENV['TEST_ENV_NUMBER'] %>.xml
```

**Comment by sj26** [comment]
Ah, yes, you were getting interleaved results.
