### ISSUE TITLE
uninitialized constant RSpecJUnitFormatter::Builder (NameError)

### ISSUE THREAD

**Issue by kimh** [sj26/rspec_junit_formatter#36]
I got the following error when I run rspec with junit formatter. It seems `RSpecJUnitFormatter::Builder` is not loaded.

I manually edited `/home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/gems/rspec_junit_formatter-0.2.3/lib/rspec_junit_formatter.rb:15` and change to use `::Builder` but no luck.

Do you have any ideas?

**Full stacktrace**

```
RAILS_ENV=test bundle exec rspec  --format RspecJunitFormatter spec/lib/mydummyapp/resolve_barriers_spec.rb
/home/ubuntu/MyDummpyApp/spec/rails_helper.rb:9:in `<top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

Top 1 slowest examples (24.41 seconds, 99.6% of total time):
  AOP::ResolveBarriers#call executes that object of the aop
    24.41 seconds ./spec/lib/mydummyapp/resolve_barriers_spec.rb:11
Coverage report generated for RSpec to /home/ubuntu/MyDummpyApp/coverage. 5456 / 39213 LOC (13.91%) covered.
/home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/gems/rspec_junit_formatter-0.2.3/lib/rspec_junit_formatter.rb:15:in `xml': uninitialized constant RSpecJUnitFormatter::Builder (NameError)
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/gems/rspec_junit_formatter-0.2.3/lib/rspec_junit_formatter.rb:19:in `xml_dump'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/gems/rspec_junit_formatter-0.2.3/lib/rspec_junit_formatter/rspec3.rb:19:in `dump_summary'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/reporter.rb:189:in `block in notify'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/reporter.rb:188:in `each'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/reporter.rb:188:in `notify'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/reporter.rb:167:in `block in finish'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/reporter.rb:175:in `close_after'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/reporter.rb:156:in `finish'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/reporter.rb:79:in `report'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/runner.rb:113:in `run_specs'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/runner.rb:89:in `run'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/runner.rb:73:in `run'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/lib/rspec/core/runner.rb:41:in `invoke'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bundler/gems/rspec-core-10dcc7aa1942/exe/rspec:4:in `<top (required)>'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bin/rspec:23:in `load'
        from /home/ubuntu/MyDummpyApp/vendor/bundle/ruby/2.2.0/bin/rspec:23:in `<main>'
```

**Gemfile.lock**

```
<snip>
    rspec_junit_formatter (0.2.3)
      builder (< 4)
      rspec-core (>= 2, < 4, != 2.12.0)
<snip>
```

**Comment by sj26** [comment]
Do you have a file called "builder.rb"? rspec_junit_formatter requires the builder gem which doesn't seem to be loaded, but [it is being required](https://github.com/sj26/rspec_junit_formatter/blob/master/lib/rspec_junit_formatter.rb#L2). Could you paste the complete result of:

    bundle exec ruby -r bundler/setup -I lib -r builder -e 'puts(*$LOADED_FEATURES)'

**Comment by kimh** [comment]
Here is the output.

```
bundle exec ruby -r bundler/setup -I lib -r builder -e 'puts(*$LOADED_FEATURES)'
enumerator.so
rational.so
complex.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/encdb.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/trans/transdb.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/unicode_normalize.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/rbconfig.rb
thread.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/thread.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/compatibility.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/defaults.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/deprecate.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/errors.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/version.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/platform.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/stub_specification.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/util/stringio.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/exceptions.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/pathname.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/pathname.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/constants.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/path_support.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/io/console.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/user_interaction.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/etc.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/config_file.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/ext/build_error.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/ext/configure_builder.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/delegate.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tmpdir.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tempfile.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/ext/ext_conf_builder.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/ext/rake_builder.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/optparse.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/command.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/ext/cmake_builder.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/ext.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/rubygems_integration.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/current_ruby.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/shared_helpers.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/gem_path_manipulation.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/gem_helpers.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/match_platform.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/rubygems_ext.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/version.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/rfc2396_parser.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/rfc3986_parser.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/common.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/generic.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/ftp.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/http.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/https.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/ldap.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/ldaps.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/mailto.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/settings.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/digest.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/digest.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/digest/sha1.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/set.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/definition.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/dependency.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/ruby_dsl.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/dsl.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/source_list.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/source.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/socket.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/socket.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/protocol.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/zlib.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/stringio.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/exceptions.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/header.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/windows_31j.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/generic_request.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/request.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/requests.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/response.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/responses.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/proxy_delta.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/backward.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/date_core.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/date.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/time.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request/http_pool.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request/https_pool.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request/connection_pools.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/request.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/cgi/core.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/cgi/util.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/cgi/cookie.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/cgi.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/uri_formatter.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/openssl.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/bn.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/cipher.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/config.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/digest.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/x509.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/buffering.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/fcntl.so
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl/ssl.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/openssl.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/securerandom.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/resolv.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/text.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/name_tuple.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/spec_fetcher.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/source/rubygems.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/ruby_version.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/source/path.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/source/git.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/strscan.so
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/lockfile_parser.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/lazy_specification.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/forwardable.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/spec_set.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/environment.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/runtime.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/dep_proxy.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/index.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/remote_specification.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/endpoint_specification.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/source/git/git_proxy.rb
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/setup.rb
/home/ubuntu/AOTv2/vendor/cache/Aspose_Cloud_SDK_For_Ruby-eda26b39ed69/lib/Barcode/builder.rb
```

**Comment by sj26** [comment]
Yes, that last line is the issue. Something in your project is overtaking the "builder" file. You'll need to correct your library dependencies to use this gem.

**Comment by sj26** [comment]
Specifically the gem should not be adding all of its directories to the require_paths:

https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_Ruby/blob/master/asposecloud.gemspec#L19

**Comment by kimh** [comment]
@sj26 Thanks for your super quick response! Let me remove the gem and try again. I'll  close this ticket once I could confirm the fix.

**Comment by sj26** [comment]
I've pushed a commit upstream to try and fix that gem, too.

**Comment by sj26** [comment]
Upstream PR has been merged.

**Comment by kimh** [comment]
Thanks so much!
